### ISSUE TITLE
Controller functions are called twice

### ISSUE THREAD

**Issue by senky** [roots/sage-woocommerce#19]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing issue
* [x] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description

Archive product template is causing a dedicated controller to be called twice.

## Steps to reproduce

1. Create `archive-product.blade.php` in your views. It can be empty.
2. Create `TaxonomyProduct_cat.php` controller with this content:
```
<?php

namespace App\Controllers;

use Sober\Controller\Controller;

class TaxonomyProduct_cat extends Controller
{
	public function test()
	{
		echo 'a';
		return '';
	}
}

```

**Expected behavior:** See only one 'a'.

**Actual behavior:** 'aa', controller data are generated two times.

**Reproduces how often:** 100%

## Versions

roots/sage-woocommerce@1.0.3

## Additional information

I think the problem is that `woocommerce_before_template_part` action is called. I am not sure why, I do not load any template parts inside my `archive-product.blade.php`.

**Comment by sven-ra** [comment]
My controllers are not working in the first place. 
Did you change anything to get them working?

**Comment by AdamQuadmon** [comment]
This also happen without Controllers.
Seems related to `apply_filters("sage/template/{$class}/data", $data);`

https://github.com/roots/sage-woocommerce/blob/def4d3db371e10b6114c37ec1da67b0e9bceadac/src/woocommerce.php#L37-L51

I created a new topic on Roots Discourse abut this:
https://discourse.roots.io/t/sage9-woocommerce-sage-template-class-data-called-on-each-template-load/17601

Now I will try the Sage10 way
