### ISSUE TITLE
Undefined variable: $args in cart/mini-cart-blade.php

### ISSUE THREAD

**Issue by besrabasant** [roots/sage-woocommerce#6]
I am working on a **woo-commerce** theme following the instructions that are given in **Readme.md** regarding porting `PHP` templates to `blade` templates.

I am facing an issue in `cart/mini-cart.blade.php`

In the **original template** in [this](https://github.com/woocommerce/woocommerce/blob/bfa36fe9233042f2fd85a3a215c5604740344552/templates/cart/mini-cart.php#L28) line, there is a **variable** named `$args` that is reporting an `Undefined variable: $args` in my `blade` template. 

How do I get values for this `$args` variable?

**Comment by mejta** [comment]
Hi, $args are extracted, so you should be able to access the variable directly.
So as a workaround, instead of `$args['list_class']`, please use `$list_class`. I will work on a fix that will solve it.

**Comment by besrabasant** [comment]
and again in [here](https://github.com/woocommerce/woocommerce/blob/64c9b5fc6ab5779255372a11209a149a15aef497/templates/loop/add-to-cart.php#L33) in my `blade` templates.

**Comment by mejta** [comment]
I will fix it tomorrow.
